{config, pkgs, ...}:
{
  # List packages installed in system profile. To search, run:
  # $ nix search wget
 environment.systemPackages = with pkgs; [
   vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
   wget
   systemd
   git
   alacritty
   btop
   gedit
   syncthing
   otpclient
   gcc
   rofi-wayland
   amdgpu_top
   clipse
   wl-clipboard
   gamemode
   #amdvlk
   nvtopPackages.full
   #amdenc
   steam
   neofetch
   obsidian
   lutris
   heroic
   gnumake
   fzf
   eza
   bat
   vscode
   vscodium
   spotify
   pwvucontrol
   gparted
   ferium
   discord
   appimage-run
   python312Packages.pip
   nodejs_24
   cargo
   ripgrep
   lazygit
   neovim
   qbittorrent
   goverlay
   mangohud
   mesa-demos
   vulkan-tools
   vkbasalt
   build2
   mesa
   yazi
   swi-prolog
   ghc
   tldr
   shotcut
   haruna 
   kdePackages.qtbase
   unzip
   kissat
   xwallpaper
   protonup-qt
   bluez
   bluez-alsa
   linuxKernel.packages.linux_zen.xpadneo
   linuxKernel.packages.linux_xanmod_latest.xone
   tmux
   blender
   godot_4
   androidStudioPackages.dev
   xfce.thunar
   hyprpaper
   waybar
   networkmanagerapplet
   hyprlock
   cava
   playerctl
   zsh-syntax-highlighting
   zsh-autosuggestions
   starship
   thefuck
   usbutils
   udiskie
   udisks
   gvfs
   rclone
   hyprshot
   firefox
   audacity
   jdk23
   python3Full
   conky
   zoxide
   hyprcursor
   bibata-cursors
   virt-viewer
   rofi-network-manager
   asusctl
   supergfxctl
   ueberzugpp
   kdePackages.okular
   swaynotificationcenter
   (sddm-astronaut.override {
   	embeddedTheme = "pixel_sakura";
   })
   lazygit
   swayosd
];
 
  fonts.packages = with pkgs; [
      nerd-fonts._0xproto
  ];
}
